# Generated by Django 3.0.7 on 2020-06-15 21:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amenity', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('addr_street', models.CharField(default='', max_length=300, null=True)),
                ('addr_city', models.CharField(default='', max_length=100, null=True)),
                ('addr_country', models.CharField(default='', max_length=100, null=True)),
                ('addr_housenumber', models.CharField(default='', max_length=30, null=True)),
                ('wheelchair', models.CharField(default='', max_length=10, null=True)),
                ('addr_postcode', models.CharField(default='', max_length=10, null=True)),
                ('phone', models.CharField(default='', max_length=50, null=True)),
                ('source', models.CharField(default='', max_length=100, null=True)),
                ('brewery', models.CharField(default='', max_length=100, null=True)),
                ('smoking', models.CharField(default='', max_length=50, null=True)),
                ('food', models.CharField(default='', max_length=50, null=True)),
                ('internet_access', models.CharField(default='', max_length=50, null=True)),
                ('website', models.CharField(default='', max_length=300, null=True)),
                ('outdoor_seating', models.CharField(default='', max_length=50, null=True)),
                ('delivery', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=300, null=True)),
                ('addr_state', models.CharField(default='', max_length=100, null=True)),
                ('opening_hours_covid19', models.CharField(default='', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
